-- Add missing columns to nights table
ALTER TABLE nights 
ADD COLUMN IF NOT EXISTS date DATE,
ADD COLUMN IF NOT EXISTS day_of_week VARCHAR(10) CHECK (day_of_week IN ('Friday', 'Saturday')),
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS max_capacity INTEGER DEFAULT 20,
ADD COLUMN IF NOT EXISTS start_time TIME DEFAULT '17:00',
ADD COLUMN IF NOT EXISTS end_time TIME DEFAULT '21:00',
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Add missing columns to time_slots table  
ALTER TABLE time_slots
ADD COLUMN IF NOT EXISTS max_orders INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS current_orders INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

